### ISSUE TITLE
help prints --dir but its not in the parse options list

### ISSUE THREAD

**Issue by WolfgangLugmayr** [leschzinerlab/Motion-correction#1]
$ runLMBFGS_relion.py -h 
Usage: runLMBFGS_relion.py --dir=<folder with micrographs> --bin=<binning>

**Comment by mcianfrocco** [comment]
Thanks for point this out @WolfgangLugmayr - that was an extraneous input option that was not used.

All you need is a starfile and a particle radius, and then any other options you'd like, but there are defaults already provided.
