### ISSUE TITLE
iminfo problems

### ISSUE THREAD

**Issue by WolfgangLugmayr** [leschzinerlab/Motion-correction#2]
iminfo cannot read our mrc files? 
maybe update to e2iminfo.py since a lot of locations do not have eman1 installed anymore.

$ iminfo 20151224_hole3only_1_00053k2gr_00239k2sq_v03_00037k2hl_00002k2ed.frames.mrc
EMAN 1.9 Cluster ($Date: 2009/02/18 05:12:22 $).
Run 'iminfo help' for detailed help.
20151224_hole3only_1_00053k2gr_00239k2sq_v03_00037k2hl_00002k2ed.frames.mrc contains 1 images in MRC or unknown format
Invalid MRC file
0. 10x10    0.00 0.00 0.00  5.00,5.00   0  SerialEMCCD: Dose frac. image, scaled by 1.00  r/f 0    07-Jan-16  19:33:39  
This image will occupy 400.0 bytes of memory

$ e2iminfo.py 20151224_hole3only_1_00053k2gr_00239k2sq_v03_00037k2hl_00002k2ed.frames.mrc
20151224_hole3only_1_00053k2gr_00239k2sq_v03_00037k2hl_00002k2ed.frames.mrc  1 images in MRC format 3710 x 3838 x 25
representing 0 particles

Traceback (most recent call last):
  File "runLMBFGS_relion.py", line 309, in <module>
    movieDIMX=subprocess.Popen("iminfo %s" %(glob.glob('Micrographs/*%s.%s'%(params['movieEXT1'],params['movieEXT2']))[0]), shell=True, stdout=subprocess.PIPE).stdout.read().strip().split('\n')[3].split('\t')[0].split('x')[0].split()[-1]
IndexError: list index out of range

**Comment by mcianfrocco** [comment]
Thanks for the suggestion @WolfgangLugmayr ! I updated the code to use e2iminfo.py instead of iminfo, and also now allow users to specify micrograph dimensions and particle box size, in case e2iminfo isn't able to read micrograph dimensions.
