### ISSUE TITLE
--trialrun IndexError

### ISSUE THREAD

**Issue by WolfgangLugmayr** [leschzinerlab/Motion-correction#3]
Traceback (most recent call last):
  File "runLMBFGS_relion.py", line 380, in <module>
    testMic=linecache.getline(params['starfile'],20).split()[3].split('@')[-1]
IndexError: list index out of range

line 20 is in our starfile:
_rlnClassNumber #16 

so the source could be fixed as follows:

```
#Get boxsize of particles
try:
    testMic=linecache.getline(params['starfile'],20).split()[3].split('@')[-1]
except IndexError:
    testMic=linecache.getline(params['starfile'],40).split()[3].split('@')[-1]
```

**Comment by mcianfrocco** [comment]
Thanks for catching that - just updated the code with your suggestion. I apologize for these clunky errors, and I appreciate your patience!
